[package]
name = "minitask3reportcard"
version = "0.1.0"
edition = "2024"


[dependencies]
printpdf = "0.3.4"
chrono = "0.4"          # for adding current date to report
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"      # optional, in case you want to save data
